image: node:22.11.0 # Use the latest stable Node.js version

stages:
  - install
  - build
  - dockerize
  - deploy

# Cache node_modules for faster installs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# Install dependencies
install_dependencies:
  stage: install
  script:
    - yarn install # Ensures clean install of dependencies
  only:
    - main

# Build the Vite project
build_project:
  stage: build
  script:
    - yarn run build
  artifacts:
    paths:
      - dist/ # Store build output as an artifact
  only:
    - main

# Dockerize and push to GitLab Container Registry
docker_build_push:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  script:
    - echo "$@blackstar9$" | docker login -u "$DixonKH" --password-stdin "$CI_REGISTRY"
    - docker build -t $IMAGE_NAME -f Dockerfile.
    - docker push $IMAGE_NAME
  only:
    - main

# Deploy to Hostinger using SSH
deploy_to_hostinger:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
  script:
    - ssh -o StrictHostKeyChecking=no $HOSTINGER_USER@$HOSTINGER_IP "
     cd /path/to/your/project &&
      git pull &&
      docker-compose down &&
      docker-compose up --build -d
      "
  only:
    - main

