image: node:22.11.0 # Use the latest stable Node.js version

stages:
  - install
  - build
  - deploy

# Cache node_modules for faster installs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# Install dependencies
install_dependencies:
  stage: install
  script:
    - yarn install # Ensures clean install of dependencies
  only:
    - main

# Build the Vite project
build_project:
  stage: build
  script:
    - yarn run build
  artifacts:
    paths:
      - dist/ # Store build output as an artifact

# Deploy to GitLab Pages
pages: 
  stage: deploy
  script:
    - mv dist public # GitLab Pages expects the output to be in a folder named 'public'
  artifacts:
    paths:
      - public
  only:
    - main


